### ISSUE TITLE
NoSuchMethodError caused by incompatible version of bundled Gson in Spigot

### ISSUE THREAD

**Issue by Configurable** [MelonDevelopment/CubedPay-Java#2]
Hello there, upon attempting to request a payment through the Java client, I was met with a NoSuchMethodError caused by a suspected incompatibility with the bundled Gson in Spigot.

Spigot Version: 1.8.8 (git-Spigot-21fe707-e1ebe52)

The code trying to ran:
https://hastebin.com/tazugomabe.cs

The stacktrace:
https://hastebin.com/wosumoqepe.md

**Comment by xIGBClutchIx** [comment]
Can you possibly try this jar that is in [this zip](https://github.com/MelonDevelopment/CubedPay-Java/files/1901226/CubedPay-bukkit-1.0.0.jar.zip) (sorry blame GitHub for it being zipped)? Seems to be working on my end made a couple changes to hopefully fix any future issues with commit 597c04fd56bc9972440c515b5c927d728ecd869f.

**Comment by Configurable** [comment]
Will try it first thing tomorrow and comment on how it went.

**Comment by Configurable** [comment]
Alright, I tried out the new jar and it does not solve the issue. Additionally, it throws a CubedPayException of "Missing required scope (app): shop-event-feed"

Full stacktrace: https://hastebin.com/ixeyosiwak.md

**Comment by xIGBClutchIx** [comment]
Fixed with 90fa181bed50a8a8592c3bc130388217d035a70d
